name: manual-workflow

on:
  issue_comment:
    types: created
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       type: choice
  #       description: Who to greet
  #       options:
  #       - monalisa
  #       - cschleiden
  #     message:
  #     environment:
  #       type: environment

jobs:
  build:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
          echo "Comment body #${{ github.event.comment.body }}"
      - uses: cybozu/octoken-action@v1
        id: octoken
        with:
          github_app_id: 155410
          github_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: niteoweb/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.issue.number }}
          state: ${{ github.event.comment.body }} # error | failure | pending | success
          repository:
          context: default
          description: this is sample status
        env:
          GITHUB_TOKEN: ${{ steps.octoken.outputs.token }}

#       - uses: actions/checkout@v2

      - name: Print secret value
        run: |
          echo secret = ${{env.SECRET_ENV}}
          echo secret = ${{env.SECRET_ENV}} | wc -c
      # - name: Print printenv
      #   run: printenv
