name: slack-notify-test

on:
  push: {}

jobs:
  expect-success:
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Send notification to Slack
        uses: kyontan/slack-notify-action@v0.1.9
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          JOB_STATUS: ${{ job.status }}
  expect-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Send notification to Slack
        uses: kyontan/slack-notify-action@v0.1.9
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          JOB_STATUS: ${{ job.status }}
      - name: exit 1
        run: exit 1
  expect-cancelled:
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Send notification to Slack
        uses: kyontan/slack-notify-action@v0.1.9
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          JOB_STATUS: ${{ job.status }}
      - name: sleep
        run: sleep 60
      - name: exit 1
        run: exit 1
