name: slack-notify-test-success

on:
  push: {}

jobs:
  edit-status:
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Send notification to Slack
        uses: kyontan/slack-notify-action@v0.1.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
