on:
  push:
    branches:
      - test-generated-files

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      # required to push a commit
      contents: write
      # required to create a pull request
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      # something to generate files
      - run: |
          echo hello > greeting

      # push the change if exists
      - uses: int128/update-generated-files-action@v2
        id: generated-files
      - run: |
          echo "the pr number is ${{ steps.generated-files.outputs.pr-number }}"